### ISSUE TITLE
Getting the raw text of current line

### ISSUE THREAD

**Issue by pnewman8** [slorion/nlight#16]
For each record of `DelimitedRecordReader`, I need to get the raw text of the line. The reason is to show the user a list of records that were rejected. (The rejection may have been because of invalid text formatting, but more likely because of subsequent processing of the fields array.)

I can't see a way to do this currently. Is it possible? I considered overriding `ReadCore`, then reading it from the buffer, but that won't work because the buffer can be refilled mid-record.

I also looked at the predecessor project `LumenWorks.Framework.IO`, but I don't think it's possible there either.

**Comment by slorion** [comment]
Since as you observed, this is a forward-only buffered reader and a line can span one or more buffers, there is no straightforward way to get the current line. The reader could keep track of it, but doing so would incur a significant performance hit. That being said, when there is a parsing error, the exception will contain the current buffer content.
