### ISSUE TITLE
Break out the dependency-free stuff

### ISSUE THREAD

**Issue by xecrets** [slorion/nlight#9]
Hi, great stuff here. I'd like to use CSV-functions, but the nuget package includes the reactive packages which in turn now includes a zillion references which are entirely unneeded for the CSV code, and much of the rest.

Most of the core features in the repo are actually entirely free of external dependencies. I'd be willing to separate them into two packages - but before I do so, I'd like to know that you're interested in accepting such a pull request and the new repo. If you'd like to inbox me, send an email to info@axcrypt.net .

**Comment by slorion** [comment]
While having a single purpose library is not a bad idea per se, I am not inclined to go down that road. I want this library to be a toolkit, because really, it is quite small and simple, and trying to isolate each functionalities into its own library would itself create a dependency tree and would become a chore to maintain and publish.

That being said, I do try to minimize external dependencies to a minimum. Having used Rx.NET for a while, I feel it is so useful that it should positively be included in most if not all .NET projects. And so, I made the decision to add it as a hard dependency. If you are not using Rx.NET, the only thing that it does is clutter your references and take up some disk space.

**Comment by xecrets** [comment]
Thanks for the reply.

If you change your mind, let me know and the offer still stands hopefully!

Regards,

Svante
